name: trucode-go
services:
  api:
    build:
      context: .
      args:
        - PORT=8080
    ports:
      - 80:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
